// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require("selenium-webdriver/chrome")
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    var chromeOptions = new chrome.Options();
    chromeOptions.addArguments("--headless");
    driver = await new Builder().setChromeOptions(chromeOptions).forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://thedemosite.co.uk/")
    await driver.findElement(By.linkText("3. Add a User")).click()
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("test")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("pass")
    await driver.findElement(By.name("FormsButton2")).click()
    await driver.findElement(By.linkText("4. Login")).click()
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("test")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("pass")
    await driver.findElement(By.name("FormsButton2")).click()
    assert(await driver.findElement(By.css("center > b")).getText() == "**Successful Login**")
  })
})
